// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUESThYgCGsMtdo8bA_CI9h919bbR1sTE',
    appId: '1:463366725624:web:4cd0ba03d8b1e1a6f6800d',
    messagingSenderId: '463366725624',
    projectId: 'student-buddy-10eff',
    authDomain: 'student-buddy-10eff.firebaseapp.com',
    storageBucket: 'student-buddy-10eff.appspot.com',
    measurementId: 'G-R05ZGGD72S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQhcHMrmIBfZ2jx92xpuwgkEPgunaY68',
    appId: '1:463366725624:android:009ee16103a8fe80f6800d',
    messagingSenderId: '463366725624',
    projectId: 'student-buddy-10eff',
    storageBucket: 'student-buddy-10eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifphLBU5IzOlaUPXt7AuDVjwBHRB1CnE',
    appId: '1:463366725624:ios:f8f2d2a305feaa62f6800d',
    messagingSenderId: '463366725624',
    projectId: 'student-buddy-10eff',
    storageBucket: 'student-buddy-10eff.appspot.com',
    androidClientId: '463366725624-re9576ushiq3fecikvsiamlm75hrr3db.apps.googleusercontent.com',
    iosClientId: '463366725624-jhmrk8s3vbivibj1cdrg3r66o38dnepp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDifphLBU5IzOlaUPXt7AuDVjwBHRB1CnE',
    appId: '1:463366725624:ios:f8f2d2a305feaa62f6800d',
    messagingSenderId: '463366725624',
    projectId: 'student-buddy-10eff',
    storageBucket: 'student-buddy-10eff.appspot.com',
    androidClientId: '463366725624-re9576ushiq3fecikvsiamlm75hrr3db.apps.googleusercontent.com',
    iosClientId: '463366725624-jhmrk8s3vbivibj1cdrg3r66o38dnepp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentBuddy',
  );
}
